export const contactData = [
  {
    employeeId: "01",
    name: "John Doe",
    email: "johndoe@email.com",
    position: "Frontend Developer",
    type: "m",
  },
  {
    employeeId: "02",
    name: "Sara",
    email: "sara@email.com",
    position: "HR Executive",
    type: "f",
  },
  {
    employeeId: "03",
    name: "Mike",
    email: "mike@email.com",
    position: "Backend Developer",
    type: "f",
  },
  {
    employeeId: "03",
    name: "Mike",
    email: "mike@email.com",
    position: "Backend Developer",
    type: "f",
  },
  {
    employeeId: "03",
    name: "Mike",
    email: "mike@email.com",
    position: "Backend Developer",
    type: "f",
  },
  {
    employeeId: "03",
    name: "Mike",
    email: "mike@email.com",
    position: "Backend Developer",
    type: "f",
  },
  {
    employeeId: "03",
    name: "Mike",
    email: "mike@email.com",
    position: "Backend Developer",
    type: "f",
  },
  {
    employeeId: "03",
    name: "Mike",
    email: "mike@email.com",
    position: "Backend Developer",
    type: "f",
  },
  {
    employeeId: "03",
    name: "Mike",
    email: "mike@email.com",
    position: "Backend Developer",
    type: "f",
  },
  {
    employeeId: "03",
    name: "Mike",
    email: "mike@email.com",
    position: "Backend Developer",
    type: "f",
  },
  {
    employeeId: "03",
    name: "Mike",
    email: "mike@email.com",
    position: "Backend Developer",
    type: "f",
  },
  {
    employeeId: "03",
    name: "Mike",
    email: "mike@email.com",
    position: "Backend Developer",
    type: "f",
  },
  {
    employeeId: "03",
    name: "Mike",
    email: "mike@email.com",
    position: "Backend Developer",
    type: "f",
  },
  {
    employeeId: "03",
    name: "Mike",
    email: "mike@email.com",
    position: "Backend Developer",
    type: "f",
  },
];
