export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";
export const DISPLAY_MISMATCH_ALERT = "DISPLAY_MISMATCH_ALER";

//user Register
export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

//user Login
export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

//add contact
export const ADD_CONTACT_BEGIN = "ADD_CONTACT_BEGIN";
export const ADD_CONTACT_SUCCESS = "ADD_CONTACT_SUCCESS";
export const ADD_CONTACT_ERROR = "ADD_CONTACT_ERROR";

//get all contacts
export const GET_ALL_CONTACTS_BEGIN = "GET_ALL_CONTACTS_BEGIN";
export const GET_ALL_CONTACTS_SUCCESS = "GET_ALL_CONTACTS_SUCCESS";

//update contact
export const UPDATE_CONTACT_BEGIN = "UPDATE_CONTACT_BEGIN";
export const UPDATE_CONTACT_SUCCESS = "UPDATE_CONTACT_SUCCESS";
export const UPDATE_CONTACT_ERROR = "UPDATE_CONTACT_ERROR";

//delete contact
export const DELETE_CONTACT_BEGIN = "DELETE_CONTACT_BEGIN";

export const SET_EDIT_CONTACT = "SET_EDIT_CONTACT";
